# Generated by Django 4.1.9 on 2023-06-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcmeWebhookMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("received_at", models.DateTimeField()),
                ("payload", models.JSONField(default=None, null=True)),
            ],
            options={
                "ordering": ["received_at"],
            },
        ),
        migrations.AddIndex(
            model_name="acmewebhookmessage",
            index=models.Index(
                fields=["received_at"], name="netbox_webh_receive_769ba8_idx"
            ),
        ),
    ]
