# Generated by Django 4.1.9 on 2023-06-21 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_webhook_receiver", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AcmeWebhookMessage",
            new_name="WebhookMessage",
        ),
        migrations.RenameIndex(
            model_name="webhookmessage",
            new_name="netbox_webh_receive_6a2187_idx",
            old_name="netbox_webh_receive_769ba8_idx",
        ),
    ]
