# Generated by Django 4.1.9 on 2023-06-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_job_created_auto_now"),
        ("netbox_webhook_receiver", "0002_webhookreceiver_store_payload"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookreceiver",
            name="datasource",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.datasource",
            ),
        ),
    ]
