# Generated by Django 4.1.9 on 2023-06-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "netbox_webhook_receiver",
            "0002_rename_acmewebhookmessage_webhookmessage_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookReceiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("originator_type", models.CharField(max_length=30)),
                ("uuid", models.UUIDField()),
                ("token", models.CharField(max_length=50)),
                (
                    "token_name",
                    models.CharField(default="X-Gitlab-Token", max_length=50),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("comments", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("name", "originator_type"),
            },
        ),
    ]
