# Generated by Django 4.1.9 on 2023-06-23 10:42

from django.db import migrations, models
import taggit.managers
import utilities.json


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0092_delete_jobresult"),
        ("netbox_webhook_receiver", "0003_webhookreceiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookreceiver",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="webhookreceiver",
            name="custom_field_data",
            field=models.JSONField(
                blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder
            ),
        ),
        migrations.AddField(
            model_name="webhookreceiver",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="webhookreceiver",
            name="tags",
            field=taggit.managers.TaggableManager(
                through="extras.TaggedItem", to="extras.Tag"
            ),
        ),
    ]
