# Generated by Django 4.1.9 on 2023-06-23 21:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_webhook_receiver", "0004_webhookreceiver_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookreceiver",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
